[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "blackbox"
version = "0.1.0"
description = "Request recording and replay debugging middleware for Django"
authors = [
    {name = "ashi"}
]
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "Django>=3.2"
]

classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

[tool.setuptools.packages.find]
where = ["blackbox_project"]
include = ["blackbox*"]
