# Generated by Django 6.1 on 2026-02-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordedrequest',
            old_name='body',
            new_name='body_parsed',
        ),
        migrations.AddField(
            model_name='recordedrequest',
            name='body_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
