# Generated by Django 6.0.2 on 2026-03-02 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_rename_body_recordedrequest_body_parsed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replayed_at', models.DateTimeField(auto_now_add=True)),
                ('status_before', models.IntegerField()),
                ('status_after', models.IntegerField()),
                ('body_changed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('recorded_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='recorder.recordedrequest')),
            ],
        ),
    ]
