# Generated by Django 6.0.2 on 2026-03-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0003_replaylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaylog',
            name='change_score',
            field=models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='replaylog',
            name='keys_changed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaylog',
            name='lines_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaylog',
            name='lines_removed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaylog',
            name='size_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaylog',
            name='size_before',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
