# Generated by Django 6.0.2 on 2026-03-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0004_replaylog_change_score_replaylog_keys_changed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordedrequest',
            old_name='response_body',
            new_name='response_body_json',
        ),
        migrations.AddField(
            model_name='recordedrequest',
            name='response_body_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
