# Generated by Django 6.1 on 2026-03-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0005_rename_response_body_recordedrequest_response_body_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
