# Generated by Django 6.1 on 2026-03-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0006_mockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaylog',
            name='regression',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('REGRESSION', 'REGRESSION'), ('FIXED', 'FIXED'), ('CHANGED', 'CHANGED')], max_length=20, null=True),
        ),
    ]
