# Generated by Django 6.1 on 2026-03-06 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecordedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('query_string', models.TextField(blank=True)),
                ('headers', models.JSONField()),
                ('body_raw', models.TextField(blank=True, null=True)),
                ('body_parsed', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField()),
                ('response_body_json', models.JSONField(blank=True, null=True)),
                ('response_body_text', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReplayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replayed_at', models.DateTimeField(auto_now_add=True)),
                ('status_before', models.IntegerField()),
                ('status_after', models.IntegerField()),
                ('body_changed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('regression', models.CharField(blank=True, choices=[('None', 'None'), ('REGRESSION', 'REGRESSION'), ('FIXED', 'FIXED'), ('CHANGED', 'CHANGED')], max_length=20, null=True)),
                ('lines_added', models.IntegerField(blank=True, null=True)),
                ('lines_removed', models.IntegerField(blank=True, null=True)),
                ('size_before', models.IntegerField(blank=True, null=True)),
                ('size_after', models.IntegerField(blank=True, null=True)),
                ('keys_changed', models.JSONField(blank=True, null=True)),
                ('change_score', models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=10, null=True)),
                ('recorded_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='blackbox.recordedrequest')),
            ],
        ),
    ]
