# Generated by Django 6.1 on 2026-03-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackbox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockItem',
        ),
        migrations.AlterField(
            model_name='recordedrequest',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
